name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.environment }} build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [Standard, Nix]

    steps:
      - uses: actions/checkout@v6

      - if: matrix.environment == 'Standard'
        name: Set up JDK 11 and Maven
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: temurin
          cache: maven

      - if: matrix.environment == 'Nix'
        name: Install Nix
        uses: cachix/install-nix-action@v31

      - if: matrix.environment == 'Nix'
        name: Set up Nix development environment
        uses: nicknovitski/nix-develop@v1

      - name: Verify with Maven
        run: mvn -B clean verify

      - name: Generate Javadocs
        run: mvn -B javadoc:javadoc
